ci:
  skip: [pip-compile]

repos:
  # General
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-xml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: trailing-whitespace
  # Python
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args:
          - "--check-untyped-defs"
          - "--ignore-missing-imports"
        additional_dependencies:
          - PyGObject-stubs
          - name-that-hash
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  # Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [markdown, css]
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.12.0
    hooks:
      - id: pretty-format-ini
  # PIP requirements
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.4.1
    hooks:
      - id: pip-compile
        name: pip-compile requirements.in
        args:
          - --resolver=backtracking
          - --generate-hashes
          - requirements/requirements.in
        files: ^requirements/requirements.in$
      - id: pip-compile
        name: pip-compile requirements-dev.in
        args:
          - --resolver=backtracking
          - --generate-hashes
          - requirements/requirements-dev.in
        files: ^requirements/requirements-dev.in$
